### ISSUE TITLE
Wrong path for windows in file zabbix_agent.conf

### ISSUE THREAD

**Issue by maxim4** [nikimaxim/zbx-smartmonitor#1]
Could you fix pleace, the path in zabbix_agent.conf for  windows:
C:\service\zabbix_agent\smartctl-storage-discovery.ps1
because write now is not correct:
C:\service\smartctl-storage-discovery.ps1
Thanks

**Comment by nikimaxim** [comment]
Hello. 
I changed it to C:\service\smartctl-storage-discovery.ps1. You can change it at your place to any other one. (This is all for example)
Thanks

**Comment by nikimaxim** [comment]
Fix README.md
