### ISSUE TITLE
sudoers file

### ISSUE THREAD

**Issue by speculatrix** [nikimaxim/zbx-smartmonitor#12]
Hello, I suggest that it's better to have a file to go into sudoers.d

so have this as, say, _etc_sudoers.d_zabbix_smartmonitor
```
Defaults:zabbix !requiretty
zabbix  ALL=(root) NOPASSWD: /usr/sbin/smartctl
zabbix  ALL=(root) NOPASSWD: /opt/zabbix/bin/smartctl-storage-discovery.sh
```

and tell people to copy it to remote hosts thus:
```
scp -p _etc_sudoers.d_zabbix_smartmonitor 1.2.3.4:/tmp/
ssh 1.2.3.4 "sudo mv _etc_sudoers.d_zabbix_smartmonitor /etc/sudoers.d/zabbix_smartmonitor"
```

**Comment by nikimaxim** [comment]
Hi
Are you suggesting to make changes? to the project

**Comment by speculatrix** [comment]
yes, this is a feature suggestion, to put the sudo things into a separate file rather than modify /etc/sudoers

**Comment by nikimaxim** [comment]
Submit to the pull request

**Comment by speculatrix** [comment]
PRq submitted - https://github.com/nikimaxim/zbx-smartmonitor/pull/14
