### ISSUE TITLE
It's will show unsupport item key for smart version.

### ISSUE THREAD

**Issue by akong77** [nikimaxim/zbx-smartmonitor#4]
Hello,
I has install zbx-smartmonitor to agent. And import to server.But it's will unsupport item key.It's not support smartctl.version this item.How to fix it?

**Comment by nikimaxim** [comment]
Hello
Does discovery work?
Did you add everything from "zbx-smartmonitor/zabbix_agentd.conf"?
What OS?

**Comment by akong77** [comment]
OS is Debian 9
I has add zbx-smartmonitor/zabbix_agentd.conf for linux.

**Comment by nikimaxim** [comment]
Perform in bash: " smartctl --version | grep -Eo "^smartctl\s[0-9\.[:space:]\r-]+" | sed -e 's/^smartctl\s//' "
What you see?

**Comment by akong77** [comment]
It's got 6.6 2016-05-31 r4324.

**Comment by akong77** [comment]
I run this command at agent

**Comment by akong77** [comment]
Could I need install smartmontools on zabbix server?

**Comment by nikimaxim** [comment]
> Could I need install smartmontools on zabbix server?

It should be installed only where you need to monitor

**Comment by nikimaxim** [comment]
Perform in bash: zabbix_get -s host_ip -p 10050 -k "smartctl.version"

https://www.zabbix.com/documentation/4.0/ru/manual/concepts/get

**Comment by akong77** [comment]
Thanks a lot.It's fix it.

**Comment by nikimaxim** [comment]
close?
