### ISSUE TITLE
Template does not appear to work

### ISSUE THREAD

**Issue by tessierp** [nikimaxim/zbx-smartmonitor#5]
Hi,

I have installed everything on the Promox HOST, am able to get information on all my HDDs and SSDs and the zabbix-agent starts without any issues however, the only information I get on Zabbix Server 5.0 is "Smartctl version", nothing else gets sent no matter what I do.

This comes from the Promox host where the agent is installed so the setup there appears to be good :
![image](https://user-images.githubusercontent.com/6784384/103379897-398cd900-4ab5-11eb-9fee-7353b0b10916.png)

**Comment by mtibke** [comment]
Hi, 
I remember that I had a similar issue and in my case I think it was caused by the 12h delay for the discovery. After decreasing it temporarily or executing it manually the different items were created and filled with data as expected.

Regard,
Martin

**Comment by tessierp** [comment]
Hi,

Yeah I went and checked if there was something in there and found that <delay> entry and suspected I would get data after 12 hours. When you say execute it manually, you mean the script or could you tell me what you did?

**Comment by mtibke** [comment]
You can manually launch a discovery via the screen "Configuration -> Hosts", select your host and then under "Discovery Rules":
![zabbix_execute_now](https://user-images.githubusercontent.com/5798184/103397964-ca59c800-4b3a-11eb-80ca-1bbf4d69c525.png)

For more details see:
[https://www.zabbix.com/documentation/current/manual/config/items/check_now](https://www.zabbix.com/documentation/current/manual/config/items/check_now)

**Comment by nikimaxim** [comment]
@tessierp 

Hi,

Did you fix the problem?

If not:
- What OS?
- What interface are the disks connected?
- What is the output of this discovery file(execute on host(Promox)): `/opt/zabbix/smartctl-storage-discovery.sh` ?

**Comment by tessierp** [comment]
> You can manually launch a discovery via the screen "Configuration -> Hosts", select your host and then under "Discovery Rules":
> ![zabbix_execute_now](https://user-images.githubusercontent.com/5798184/103397964-ca59c800-4b3a-11eb-80ca-1bbf4d69c525.png)
> 
> For more details see:
> https://www.zabbix.com/documentation/current/manual/config/items/check_now

I tried but it didn't fix anything so I guess my problem is elsewhere.
All I get is the version for some reason.

**Comment by tessierp** [comment]
> @tessierp
> 
> Hi,
> 
> Did you fix the problem?
> 
> If not:
> 
> * What OS?
> * What interface are the disks connected?
> * What is the output of this discovery file(execute on host(Promox)): `/opt/zabbix/smartctl-storage-discovery.sh` ?

Hi there,

In answer to your questions

- PROXMOX 6.3 (which is based on Debian)
- SATA, and I did execute the scripts and all the disks show up.
- I will place the output of the execution of the script below. I did modify where this file is placed, instead of /opt/zabbix, I placed it in /etc/zabbix/scripts and yes I did modify the UserParam configuration to look at the right place.

UserParam Configuration : 
UserParameter=storage.discovery[*],/etc/zabbix/scripts/smartctl-storage-discovery.sh
UserParameter=storage.get[*],smartctl -i -H -A -l error -l background $1
UserParameter=smartctl.version,smartctl --version | grep -Eo "^smartctl\s[0-9\.[:space:]\r-]+" | sed -e 's/^smartctl\s//'

Please note that Proxmox does not use SUDO and it is not required since the system is installed as root only. This is by default and why sudo is not present.

Here is the output from the script : 

{
    "data": [{
        "{#STORAGE.SN}": "W6A1F78F",
        "{#STORAGE.MODEL}": "ST3000VN000-1HJ166",
        "{#STORAGE.NAME}": "/dev/sda",
        "{#STORAGE.CMD}": "/dev/sda -dsat",
        "{#STORAGE.SMART}": "1",
        "{#STORAGE.TYPE}": "0"
    }, {
        "{#STORAGE.SN}": "W6A1M44S",
        "{#STORAGE.MODEL}": "ST3000VN000-1HJ166",
        "{#STORAGE.NAME}": "/dev/sdb",
        "{#STORAGE.CMD}": "/dev/sdb -dsat",
        "{#STORAGE.SMART}": "1",
        "{#STORAGE.TYPE}": "0"
    }, {
        "{#STORAGE.SN}": "S21HNXAG725504A",
        "{#STORAGE.MODEL}": "Samsung SSD 850 EVO 500GB",
        "{#STORAGE.NAME}": "/dev/sdc",
        "{#STORAGE.CMD}": "/dev/sdc -dsat",
        "{#STORAGE.SMART}": "1",
        "{#STORAGE.TYPE}": "1"
    }, {
        "{#STORAGE.SN}": "20242A800218",
        "{#STORAGE.MODEL}": "WDC WDS250G2B0B",
        "{#STORAGE.NAME}": "/dev/sdd",
        "{#STORAGE.CMD}": "/dev/sdd -dsat",
        "{#STORAGE.SMART}": "1",
        "{#STORAGE.TYPE}": "1"
    }]
}

**Comment by nikimaxim** [comment]
> I tried but it didn't fix anything so I guess my problem is elsewhere.
> All I get is the version for some reason.

[Screen](https://user-images.githubusercontent.com/5798184/103397964-ca59c800-4b3a-11eb-80ca-1bbf4d69c525.png)

When "Execute now" in "Discovery roles":
- an error appears(in field "Status")?
- a items appears?

**Comment by tessierp** [comment]
An image is worth a thousand words. I don't see any errors.

![image](https://user-images.githubusercontent.com/6784384/103417776-0f412700-4b5a-11eb-9246-44c8eda794bb.png)

**Comment by tessierp** [comment]
Wait, an error occurred : Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'sh: 1: /opt/zabbix/smartctl-storage-discovery.sh: not found'

So something is still pointing to /opt/zabbix. I will have to put everything in there then.

**Comment by nikimaxim** [comment]
> Please note that Proxmox does not use SUDO and it is not required since the system is installed as root only. This is by default and why sudo is not present.

SUDO need for the "zabbix-agent" because it is executed user "zabbix"

**Comment by nikimaxim** [comment]
> Wait, an error occurred : Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'sh: 1: /opt/zabbix/smartctl-storage-discovery.sh: not found'

> SUDO need for the "zabbix-agent" because it is executed user "zabbix"

**Comment by tessierp** [comment]
> > Wait, an error occurred : Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'sh: 1: /opt/zabbix/smartctl-storage-discovery.sh: not found'
> 
> > SUDO need for the "zabbix-agent" because it is executed user "zabbix"

OK, I will install SUDO and see if it helps.

**Comment by nikimaxim** [comment]
> > > SUDO need for the "zabbix-agent" because it is executed user "zabbix"

Add in /etc/sudoers
- Defaults:zabbix !requiretty
- zabbix ALL=(root) NOPASSWD: /usr/sbin/smartctl
- zabbix ALL=(root) NOPASSWD: /etc/zabbix/scripts/smartctl-storage-discovery.sh

**Comment by tessierp** [comment]
Alright seems like adding the script in /opt/zabbix and enabling sudo made this work.

I would have a suggestion. For the UserParameter part. Instead of adding everything in zabbix_agentd.conf, I would suggest users instead enable an include 'Include=/usr/local/etc/zabbix_agentd.conf.d/*.conf' and create a file in there called 'userparameter_smartctl.conf' and put the code there instead. That way it makes it more modular. Anyways not a requirement just a suggestion.

Thanks for the help everyone!

**Comment by nikimaxim** [comment]
> Alright seems like adding the script in /opt/zabbix and enabling sudo made this work.
> 
> I would have a suggestion. For the UserParameter part. Instead of adding everything in zabbix_agentd.conf, I would suggest users instead enable an include 'Include=/usr/local/etc/zabbix_agentd.conf.d/*.conf' and create a file in there called 'userparameter_smartctl.conf' and put the code there instead. That way it makes it more modular. Anyways not a requirement just a suggestion.
> 
> Thanks for the help everyone!

I agree with you. 
we also use "UserParameter" in the "zabbix_agentd.conf.d/*.conf" file.

The manual is understandable. 
Thanks.

**Comment by tessierp** [comment]
Thanks for the help @nikimaxim !
