### ISSUE TITLE
Question regarding Disk Errors / Problems reporting

### ISSUE THREAD

**Issue by tessierp** [nikimaxim/zbx-smartmonitor#6]
Hi,

I was looking through the template but not sure exactly how and where rules are set to trigger a problem that can be seen from the Dashboard when a disk is starting to get errors, to give us time to change the disk before it stops working. Could someone point me in the right direction?

The reason is perhaps I may need to modify this to get early reports of problems.

**Comment by mtibke** [comment]
You can find them as "Trigger Prototypes" within the discovery rule ("Smartctl storage discovery" ) of the template.

**Comment by tessierp** [comment]
@mtibke  Thanks! Much appreciate!
